[package]
name = "my-rts"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "=1.0.133"
bevy = { version = "0.14", features = ["dynamic_linking", "bevy_scene"]}
bevy_panorbit_camera = "0.20.0"
bevy_framepace = "=0.17.1"
parry2d = "0.17"
